import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// Helper function to truncate long titles
function truncateTitle(title: string, maxLength: number = 40): string {
  if (title.length <= maxLength) return title;
  return title.substring(0, maxLength - 3) + "...";
}

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    "index",
    {
      type: "category",
      label: "Ubuntu Private Lab",
      link: {
        type: "doc",
        id: "ubuntu-private-lab/index",
      },
      items: [
        "ubuntu-private-lab/code-server",
        "ubuntu-private-lab/coolify-paas",
        "ubuntu-private-lab/custom-commands-library",
        "ubuntu-private-lab/docker-management",
        "ubuntu-private-lab/docker-setup",
        "ubuntu-private-lab/executable-shell-scripts",
        "ubuntu-private-lab/file-directory-management",
        "ubuntu-private-lab/ha-proxy-load-balancer",
        "ubuntu-private-lab/index",
        "ubuntu-private-lab/initial-hardening-setup",
        "ubuntu-private-lab/initial-utilities-setup",
        "ubuntu-private-lab/linux-ssh-key-generation",
        "ubuntu-private-lab/linux-timezone-management",
        "ubuntu-private-lab/mapping-sftp-connection",
        "ubuntu-private-lab/memory-swap-space",
        "ubuntu-private-lab/monitoring-resource-performance",
        "ubuntu-private-lab/nginx-proxy-manager",
        "ubuntu-private-lab/nvm-node",
        "ubuntu-private-lab/ollama-container-interaction",
        "ubuntu-private-lab/tcp-udp-ports-allocated",
        "ubuntu-private-lab/tree-view-in-linux",
        "ubuntu-private-lab/ubuntu-user-account",
        "ubuntu-private-lab/user-account-management-guide",
        "ubuntu-private-lab/vmt-virtualization-monitoring-tools",
      ],
    },
    {
      type: "category",
      label: "Landing Zone Concepts",
      link: {
        type: "doc",
        id: "landing-zone-concepts/index",
      },
      items: [
        "landing-zone-concepts/index",
        {
          type: "category",
          label: "Architecture",
          items: [
            "landing-zone-concepts/architecture/hashicorp-vault-secret",
            "landing-zone-concepts/architecture/Landing-zone-hld",
            "landing-zone-concepts/architecture/landing-zone-architecture",
          ],
        },
        {
          type: "category",
          label: "Discovery",
          items: [
            "landing-zone-concepts/discovery/cloud-platform-requirement-questionnaire",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "MS Windows",
      link: {
        type: "doc",
        id: "ms-windows/index",
      },
      items: [
        "ms-windows/ansible-installation",
        "ms-windows/ansible",
        "ms-windows/hashicorp-vault",
        "ms-windows/multi-cloud-infrastructure-platform",
        "ms-windows/terraform-multi-cloud-setup",
        {
          type: "category",
          label: "Powershell",
          items: [
            "ms-windows/powershell/powershell-creating-ssh-keys",
            "ms-windows/powershell/powershell-network-information",
            "ms-windows/powershell/powershell-symbolic-links-manual",
          ],
        },
        {
          type: "category",
          label: "WSL",
          items: [
            "ms-windows/wsl/index",
            "ms-windows/wsl/ubuntu-24.04-lts",
            "ms-windows/wsl/setup-windows-subsystem-for-linux",
            "ms-windows/wsl/setup-wsl-putty-connection",
            "ms-windows/wsl/lifecycle-operations",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Kubernetes",
      link: {
        type: "doc",
        id: "kubernetes/kubernetes-index",
      },
      items: [
        "kubernetes/architecture-components",
        "kubernetes/architecture-diagram",
        "kubernetes/deployment-guide",
        "kubernetes/getting-started-guide",
        {
          type: "category",
          label: "Home Lab",
          items: [
            "kubernetes/home-lab/getting-started-home-lab",
            "kubernetes/home-lab/home-lab",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Ansible",
      link: {
        type: "doc",
        id: "ansible/index",
      },
      items: [
        "ansible/index",
        "ansible/ansible-core-concepts",
        "ansible/ansible-ubuntu-hardining-palybook",
        "ansible/set-discovered-dhcp-ip",
      ],
    },
    {
      type: "category",
      label: "Git",
      link: {
        type: "doc",
        id: "git/index",
      },
      items: [
        "git/index",
        "git/git-new-branch-in-repo",
        "git/starting-a-new-git-repo",
      ],
    },
    {
      type: "category",
      label: "AWS",
      link: {
        type: "doc",
        id: "aws/aws-index",
      },
      items: [
        {
          type: "category",
          label: "Fundamentals",
          items: [
            "aws/fundamentals/index",
            "aws/fundamentals/fundamentals-global-infrastructure",
            "aws/fundamentals/identity-access-management-iam",
            "aws/fundamentals/network-security-architecture",
            "aws/fundamentals/data-protection-encryption",
            "aws/fundamentals/compute-application-security",
            "aws/fundamentals/management-governance",
            "aws/fundamentals/compliance-regulatory-adherence",
            "aws/fundamentals/hybrid-cloud-connectivity",
            "aws/fundamentals/disaster-recovery-business-continuity",
            "aws/fundamentals/devsecops-automation",
            "aws/fundamentals/cost-management-optimization",
            "aws/fundamentals/monitoring-detection-response",
            "aws/fundamentals/architecture-systems_engineering-principles",
            "aws/fundamentals/government-specific-aws-project-aspects",
            "aws/fundamentals/advanced-aws-topics-emerging-technologies",
          ],
        },
        {
          type: "category",
          label: "Architecture",
          link: {
            type: "doc",
            id: "aws/architecture/index",
          },
          items: [
            "aws/architecture/index",
            "aws/architecture/multi-azs-secured-networking-hybrid",
            "aws/architecture/aws-advance-pass-architecture",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Knowledge Base",
      link: {
        type: "doc",
        id: "heap-knowledge-base/index",
      },
      items: [
        "heap-knowledge-base/index",
        "heap-knowledge-base/api-gateways",
        "heap-knowledge-base/api-security",
        "heap-knowledge-base/apis",
        "heap-knowledge-base/aws-elastic-block-store",
        "heap-knowledge-base/aws-s3-storage-system",
        "heap-knowledge-base/aws-s3",
        "heap-knowledge-base/aws-storage-types-and-use-cases",
        "heap-knowledge-base/building-reliable-apis",
        "heap-knowledge-base/cicd-core-concepts",
        "heap-knowledge-base/clean-software-architecture",
        "heap-knowledge-base/container-orchestration",
        "heap-knowledge-base/content-delivery-networks",
        "heap-knowledge-base/database-performance-strategies",
        "heap-knowledge-base/differences-between-virtualization-and-containerization",
        "heap-knowledge-base/distributed-caching",
        "heap-knowledge-base/dns-record-types",
        "heap-knowledge-base/docker",
        "heap-knowledge-base/free-apis-for-developers",
        "heap-knowledge-base/how-ssh-works",
        "heap-knowledge-base/http-protocol-evolution",
        "heap-knowledge-base/http-request",
        "heap-knowledge-base/identity-services",
        "heap-knowledge-base/ipv4",
        "heap-knowledge-base/json-web-token",
        "heap-knowledge-base/kubernetes",
        "heap-knowledge-base/mastering-database-selection",
        "heap-knowledge-base/mcp",
        "heap-knowledge-base/message-queues",
        "heap-knowledge-base/microservices-architecture-data-sharing",
        "heap-knowledge-base/microservices-design-patterns",
        "heap-knowledge-base/microservices-sidecar-pattern",
        "heap-knowledge-base/modern-database-types",
        "heap-knowledge-base/monolith-vs-microservices",
        "heap-knowledge-base/network-access-control-list",
        "heap-knowledge-base/network-hub-and-spoke",
        "heap-knowledge-base/network-security-components-in-cloud-infrastructure",
        "heap-knowledge-base/network-tapping",
        "heap-knowledge-base/networking-the-essentials",
        "heap-knowledge-base/openid-connect",
        "heap-knowledge-base/proxy-vs-reverse-proxy",
        "heap-knowledge-base/redis-utils",
        "heap-knowledge-base/rest-api-authentication-methods",
        "heap-knowledge-base/rest-apis",
        "heap-knowledge-base/saas-functional-requirements-backbone-part-2",
        "heap-knowledge-base/security-information-and-event-management",
        "heap-knowledge-base/software-architecture-patterns",
        "heap-knowledge-base/software-architecture-resources",
        "heap-knowledge-base/strategies-to-reduce-latency",
        "heap-knowledge-base/types-of-databases",
      ],
    },
    {
      type: "category",
      label: "Cyber Security",
      link: {
        type: "doc",
        id: "cyber-security/index",
      },
      items: [
        "cyber-security/index",
        "cyber-security/information-security-and-cyber-fundamentals",
        "cyber-security/information-security-architecture",
        "cyber-security/critical-infrastructure-security",
        "cyber-security/cyber-protection-in-cloud-and-hybrid-environments",
        "cyber-security/identity-and-authorization-management-(iam)",
        "cyber-security/communication-and-network-security",
        "cyber-security/information-security-and-privacy",
        "cyber-security/application-security-and-secure-development",
        "cyber-security/monitoring,-detection-and-response-to-events",
        "cyber-security/compliance-and-regulatory-management",
        "cyber-security/architecture-and-systems-engineering-skills",
        "cyber-security/cloud-security",
        "cyber-security/enterprise-security-architecture",
        "cyber-security/incident-response-and-forensics",
        "cyber-security/security-leadership-and-communication",
      ],
    },
  ],
};

export default sidebars;
